[package]
name = "tange"
version = "0.1.0"
authors = ["Andrew Stanton <astanton@etsy.com>"]

[dependencies]
rayon = "1.0"
log = "0.4"
priority-queue = "0.5.1"
jobpool = "0.3.8"
num_cpus = "1.0"

[lib]
name = "tange"
path = "src/lib.rs"
